/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Model utilisé dans le composant register.
 */
export interface RegistrationRequest {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
}
