/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * FeedbackResponse
 * @export
 * @interface FeedbackResponse
 */
export interface FeedbackResponse {
  comment?: string;
  note?: number;
  ownFeedback?: boolean;
}
